:PROPERTIES:
:ID:       7233EF2D-04BB-4A88-9179-DC8AEE26313A
:END:
#+title: al

* TODO Increment
SCHEDULED: <1980-01-10 Thu +1d>
:PROPERTIES:
:LAST_REPEAT: [2026-07-20 Mon 10:28]
:END:
* Name

Al is the provisional name for my personal agent setup.

"Al" was chosen because:
- it's short
- it looks like "AI"...potentially indiscrenibly depending on font
- I'm planning on going fairly minimal and piling on to the
  "all you need is" cliche
- it could call you Betty

* Model Selection

There should maybe be multiple involved and I don't have a mature
selection framework as documented elsewhere, so for now I'll start
with the trendiest option du jour from [[id:5C3C29D0-540F-4F03-88CF-DE7E2C1CC028][hugging-face]].

#+name: model-file
#+begin_src shell :async no :session none :results output
  hf download --quiet empero-ai/Qwythos-9B-Claude-Mythos-5-1M-GGUF Qwythos-9B-Claude-Mythos-5-1M-MTP-Q4_K_M.gguf
#+end_src

#+RESULTS: model-file
: /Users/mwhipple/.cache/huggingface/hub/models--empero-ai--Qwythos-9B-Claude-Mythos-5-1M-GGUF/snapshots/5cebd89dd078b033c26988248740ddadf40f2fbd/Qwythos-9B-Claude-Mythos-5-1M-MTP-Q4_K_M.gguf

* Coding the Agent
:PROPERTIES:
:header-args: :var venv="/tmp/al" :python /tmp/al/bin/python :async yes :results output :session al
:END:

I'm hoping to just use [[id:701C146E-FE50-4C4D-9332-7B8BA81DAC25][llama.cpp]] as directly as possible through the
python bindings project. I've ended up moving away from richer
harnesses due to feeling like they are more likely to chase richer
functionality than I want and the perpsective that I should be able to
use the agent to help build itself (which should effectively dissolve
the traditional benefits of using more packaged software).

** Setup the venv

The dependencies are minimal. As touched on above [[id:5C3C29D0-540F-4F03-88CF-DE7E2C1CC028][hugging-face]] is an
assumed host dependency (which could also be taken care of by
[[id:701C146E-FE50-4C4D-9332-7B8BA81DAC25][llama.cpp]] but splitting out management from use seems wise for
multiple reasons).

#+begin_src bash :session al-venv
  python -m venv "${venv}"
  ${venv}/bin/python -m pip install llama-cpp-python
#+end_src

#+RESULTS:
#+begin_example
Collecting llama-cpp-python
  Using cached llama_cpp_python-0.3.34-py3-none-macosx_26_0_arm64.whl
Collecting typing-extensions>=4.5.0 (from llama-cpp-python)
  Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting numpy>=1.20.0 (from llama-cpp-python)
  Using cached numpy-2.5.1-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Collecting diskcache>=5.6.1 (from llama-cpp-python)
  Using cached diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting jinja2>=2.11.3 (from llama-cpp-python)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting MarkupSafe>=2.0 (from jinja2>=2.11.3->llama-cpp-python)
  Using cached markupsafe-3.0.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (2.7 kB)
Using cached diskcache-5.6.3-py3-none-any.whl (45 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp314-cp314-macosx_11_0_arm64.whl (12 kB)
Using cached numpy-2.5.1-cp314-cp314-macosx_14_0_arm64.whl (5.3 MB)
Using cached typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Installing collected packages: typing-extensions, numpy, MarkupSafe, diskcache, jinja2, llama-cpp-python


Successfully installed MarkupSafe-3.0.3 diskcache-5.6.3 jinja2-3.1.6 llama-cpp-python-0.3.34 numpy-2.5.1 typing-extensions-4.16.0
#+end_example

** Tools

*** Protocol

llama.cpp and/or the python bindings seem to provide some pieces to
help with dealing with tool calls so that the responses can be more
readily dealt with, but that doesn't seem to work particularly well
nor does it have a lot of documentation. This support is likely to be
particularly important when accessing through the server as that would
enable a cleaner API surface area, but when working with the models
more directly there seems to be questionable value in trying to push
that type of logic behind an abstraction rather than dealing with it
more directly. Overall if it just worked I'd use it but since it
doesn't I don't see any particular benefit to trying to provide that
handling in a way that is integrated more deeply rather than just
having that logic able to be applied; expecting less magic applied
in-flight and just expecting to apply it after the fact.

*** ToolBelt

**** Derive Tool Definition

Extracting information for use by the model should be done by
reflection. Any ambiguous information should result in an error rather
than attempting to be clever.

***** Type Definition

The first step will be defining the expected output since that's a gap
in the upstream type definitions.

Upstream basically stops at parameters so this presses on.

This doesn't seem particularly expressive, but that's probably a
larger question and probably best served by what amounts to portable
schema definition.

#+name: tool-definition-type
#+begin_src python
  from typing import List, Dict
  from typing_extensions import TypedDict, NotRequired, Literal

  class ToolDefinition(TypedDict):
    type: Literal["function"]
    function: ToolFunctionDefinition

  class ToolFunctionDefinition(TypedDict):
    name: str
    description: NotRequired[str]
    parameters: ToolFunctionDefinitionParameters

  class ToolFunctionDefinitionParameters(TypedDict):
    type: Literal["object"]
    properties: Dict[str, ToolFunctionDefinitionParameterDefinition]
    required: List[str]

  class ToolFunctionDefinitionParameterDefinition(TypedDict):
    type: str
#+end_src

#+RESULTS: tool-definition-type

***** Logic

****** is_required_parameter

Indicate whether a parameter is required.

This includes positional parameters that have no default.

#+begin_src python
  import inspect
  def is_required_parameter(param):
      return param.default is inspect.Parameter.empty and (
        param.kind not in (inspect.Parameter.VAR_POSITIONAL,
                           inspect.Parameter.VAR_KEYWORD))
#+end_src

#+RESULTS:

****** param_type

Introspect parameter types or throw trying

#+begin_src python
  def param_type(param):
      if param.annotation == inspect.Parameter.empty:
          raise TypeError(
              f"Parameter '{param['name']}' lacks a type annotation;"
              "add a type hint (e.g., def foo(x: int) -> str).")
      return str(param.annotation)
#+end_src

#+RESULTS:

****** define_tool

This is mostly cleaned up from previously produced AI input...
mostly to fully conform to the desired format.
Reference sources should be provided which is also something that
should be included in the system prompt.

This does /not/ attempt to be comprehensive. As needed this should be
extended with registries to handle additional types.

#+begin_src python
  import inspect
  def define_tool(func: callable) -> ToolFunctionDefinition:
      """
      Produce a dictionary suitable for llama-cpp-python tool registration.
      """

      description = func.__doc__
      if not description:
          raise TypeError("Function must have a non-empty docstring.")

      sig = inspect.signature(func)
      params = sig.parameters.items()

      return {
          "type": "function",
          "function": {
              "name": func.__name__,
              "description": description,
              "parameters": {
                  "type": "object",
                  "properties": {
                      param_name: {
                          "type": param_type(param),
                      }
                  for param_name, param in params},
                  "required": [param_name for param_name, param in params if is_required_parameter(param)],
              },
              "return_type": str(sig.return_annotation),
          },
      }
#+end_src

#+RESULTS:

******* Sandbox

What better way to test the definition extraction...

#+begin_src python
  from pprint import pprint
  pprint(define_tool(define_tool))
#+end_src

#+RESULTS:
#+begin_example
func: <built-in function callable>
{'function': {'description': '\n'
                             'Produce a dictionary suitable for '
                             'llama-cpp-python tool registration.\n',
              'name': 'define_tool',
              'parameters': {'properties': {'func': {'type': '<built-in '
                                                             'function '
                                                             'callable>'}},
                             'required': ['func'],
                             'type': 'object'},
              'return_type': "<class '__main__.ToolFunctionDefinition'>"},
 'type': 'function'}
#+end_example

**** apply_tool

Call a function using a ToolCallMessage and return the expected
request message.

#+begin_src python
  def apply_tool(func_call, tool: callable, id: str):
    results = tool(func_call.input)
    return { "role": "tool",
             "content": results,
             "name": func["name"],
             "tool_call_id": tool_call["id"] }
#+end_src

#+RESULTS:

**** Class Definition

The ToolBelt object will handle advertising of available tools and
their subsequent use.

Application will produce the message to send back to the model.

#+begin_src python
  class ToolBelt():
      def __init__(self):
          self.tools = {}

      def register(self, func: Callable):
          self.tools[func.__name__] = func

      def definitions(self):
          return [define_tool(tool) for tool in self.tools.values()]

      def apply(self, tool_call: ToolCall) -> ChatCompletionRequestToolMessage:
          if tool_call["type"] != "function":
              raise TypeError("Only functions suppored")
          func = tool_call["function"]
          tool_name = func["name"]
          tool = self.tools.get(tool_name)
          if tool is None:
              raise ValueError(f"Tool {tool_name} not found")
          return apply_tool(tool_call, tool)

  tool_belt = ToolBelt()
#+end_src

#+RESULTS:

*** Call Parsing and Integration

The ToolBox defined above will be oriented towards standard
interfaces, but there may be need to be some additional adaptation
between those standards and what passes to and from the model (and
maybe elsewhere).

Such adapaters will be defined separately and plugged in where
appropriate to the message passing and handling machinery...so this
defines a configuraable integration layer rather than something that
should be baked into either side.

The general interface for parsing will be one that accepts a message
and returns (possibly empty) lists of extracted information.

**** Handling Qwen Style Calls

The model I'm currently using seems to make use of Qwen style tool
calls which for whatever reason is XMLish...but not quite XML.

The matching could likely be trivially generalized to suppor a
function that takes a tag name and returns the attribute and body...
but for now this seems legible anough and below the rule of three.

The logic is organized to support [[id:E64A3393-5DD5-4446-8202-BB7588D4EB10][comprehensions]].

***** parameter_from_qwen_match

When passed a regex capture for ~<paramter={}>{}</parameter>~,
return a tuple of name and parameter value.

The match itself is done by the caller.

#+begin_src python
  import json
  def parameter_from_qwen_match(match):
      name = match.group(1).strip()
      str_value = match.group(2).strip()
      try:
          return (name, json.loads(str_value))
      except json.JSONDecodeError:
          return (name, str_value)
#+end_src

#+RESULTS:

***** call_from_qwen_match

When passed a regex capture for ~<function={}>{}</function>~,
return a tuple of name and parameter value.

the match itself is done by the caller.

#+begin_src python
  import re
  def call_from_qwen_match(match):
      return {
          "type": "function",
          "id": f"call_{uuid.uuid4().hex[:24]}",
          "function": {
              "name": match.group(1),
              "arguments": {k: v for (k, v)
                            in map(parameter_from_qwen_match,
                                   re.finditer(r'<parameter=([\w.\-]+)>([\s\S]*?)</parameter>', match.group(2)))},
          },
      }

#+end_src

#+RESULTS:

***** parse_qwen_tool_calls

#+begin_src python
  import json
  import re

  def parse_qwen_tool_calls(msg):
    """Parses Qwen style <function> and <parameter> tags from a string."""
    return [call_from_qwen_match(match) for match in
            re.finditer(r'<function=([\w.\-]+)>([\s\S]*?)</function>', msg['message'])]
#+end_src

#+RESULTS:

****** Sandbox

#+begin_src python
  print(parse_qwen_tool_calls({"message": """
  <tool_call>
  <function=read_file>
  <parameter=path>
  /Users/mwhipple/memex/cabinet/al.org
  </parameter>
  </function>
  </tool_call>"""}))
#+end_src

#+RESULTS:
: /Users/mwhipple/memex/cabinet/al.org
: [{'type': 'function', 'id': 'call_9da4e2bc8df147ff9f56c373', 'function': {'name': 'read_file', 'arguments': {'path': '/Users/mwhipple/memex/cabinet/al.org'}}}]

*** Definitions

I'll start with some basics with some manual wiring and then work on
generalizing some of that. The first goal is just making sure the tool
can be discovered and provokes a tool_call from the model.

The definition for the tools will be defined alongside the tool (and
subsequently based on code already floating around) to be pulled in by
the agent later.

The tools will be defined using type [[id:D875AD7A-32CC-4252-B42E-97B28C3835AA][ChatCompletionTool]]

The actual types here could use some help which is a lingering
upstream TODO:
https://github.com/abetlen/llama-cpp-python/blob/629bd1b333f60d24a01886c5f99019f4c7c3ea6c/llama_cpp/llama_types.py#L272
I'd mostly want to derive this information which should largely absorb
that concern. The structure below gets the ball rolling and nudges
this to the point of handling the tool call which will be the next
step. Next steps are to write what is a standlone tool handler for the
time being, pipe that back to the agent, and then bundle all of that
up as a toolbelt.

#+name: fs-tools
#+begin_src python
  def read_file(path: str) -> str:
      "Return the contents of the file at path as a string."
      try:
          with open(path, 'r', encoding='utf-8') as f:
              return f.read()
      except FileNotFoundError:
          return f"Error: File not found at {path}"
      except IOError as e:
          return f"Error reading file: {e}"
  tool_belt.register(read_file)
#+end_src

** Messages

Similar to Langchain there will be some basic factory functions for
message creation. Ideally these should be more naturally integrated
into relevant workflows, which will hopefully be ratcheted down after
there's a clear picture of how it can make sense.

These are trivial means to produce the expected dicts.

#+begin_src python
  from llama_cpp.llama_types import ChatCompletionRequestMessage

  def user_message(content: str) -> ChatCompletionRequestMessage:
      return {"role": "user", "content": content}
  def system_message(content: str) -> ChatcompletionRequestMessage:
      return {"role": "system", "content": content}
#+end_src

#+RESULTS:

** ChatDriver

When dealing with lower level interactions, it feels like one of the
main pieces is the component that handles sending messages and dealing
with responses which will be defined here as a ChatDriver.

The focus is that messgage coordination, and providing relevant
extension points to add additional behavior.

The configuration options should be defined as a separate object which
is passed in.

This could certainly benefit from a bit more encapsulation, but to
start its unclear where the best seams are that won't just create a
ball of mud.

Messages will be sent using [[id:C6047B7D-4B82-45B9-886A-FACBF966030B][create_chat_completion]].

on_message will be called on each message received from the model and
serves as the means to trigger most of the logic. This will be passed
the message and a context dictionary (to be more precisely defined).

#+begin_src python
  from llama_cpp import Llama
  from llama_cpp.llama_types import (
      ChatCompletionRequestMessage,
  )

  class ChatDriver:
      def __init__(self,
                   model: Llama,
                   on_message = ForEachMessageHandler()):
          self.model = model
          self.messages: list[ChatCompletionRequestMessage] = []
          self.on_message = on_message

      def append(self, msg: ChatCompletionRequestMessage):
          self.messages.append(msg)

      def latest(self):
          return self.messages[-1]

      def submit(self):
          resp = self.model.create_chat_completion(
              messages = self.messages,
              tools = self.tools,
              tool_choice = "auto",
              temperature=0.6,          # Official developer recommendation
              repeat_penalty=1.05,
          )
          on_message = self.on_message # assign to avoid being a method call
          on_message({"driver": self}, resp)
          choice = resp["choices"][0]
          self.messages.append(choice['message'])
#+end_src

#+RESULTS:

*** on_message

on_message will make use of the Composite pattern so that details such
as routing logic can be updated or to enable parameter enrichement.

**** ForEachMessageHandler

The initial implementation will represent a list of multiple handlers
all of which will be called (if any).

#+begin_src python
  class ForEachMessageHandler:
    def __init__(self):
        self.handlers = []
    def append_handler(self, handler):
        self.handlers.append(handler)
    def __call__(self, ctx, msg):
        for h in self.handlers:
            h(ctx, msg)
#+end_src

#+RESULTS:

** Beget Al

Construct and interact with a [[id:D40AB771-6361-484A-8685-D082565D0D1E][llama.Llama]].

There a lot of options for construction documented at [[id:E23922B9-95E0-45AA-A3FB-DB627EA18002][llama.Llama.init]].

*** main

chat_format feels like it has a broad impact but is missing some local explanation.
The current model is advertised as using Qwen/ChatML style, but when
the format is changed the tools aren't detected without further help.

#+begin_src python :var model_path=model-file() :noweb yes
  <<chat>>
  <<fs-tools>>

  from pprint import pprint
  from llama_cpp import Llama
  llm = Llama(
      model_path=model_path.strip(),
      chat_format="chatml-function-calling",
      verbose=False,
  )
  chat = Chat(llm)
  chat.register_tool(READ_FILE)
  chat.append_system_message("""

  You are my personal AI asssistant named Al.

  You not only do what is asked, but explain what you are doing
  and the reason throughout the process.

  """)

  chat.append_user_message("""

  Read the contents of this file at "/Users/mwhipple/memex/cabinet/al.org"

  """)

  resp = chat.submit()

  pprint(resp)

#+end_src

#+RESULTS:
#+begin_example
{'choices': [{'finish_reason': 'tool_calls',
              'index': 0,
              'logprobs': None,
              'message': {'content': None,
                          'function_call': {'arguments': '{ "path": '
                                                         '"/Users/mwhipple/memex/cabinet/al.org" '
                                                         '}',
                                            'name': 'read_file:'},
                          'role': 'assistant',
                          'tool_calls': [{'function': {'arguments': '{ "path": '
                                                                    '"/Users/mwhipple/memex/cabinet/al.org" '
                                                                    '}',
                                                       'name': 'read_file'},
                                          'id': 'call__0_read_file_cmpl-0a6820f6-ab68-4089-aeaa-8dc97c7189bb',
                                          'type': 'function'}]}}],
 'created': 1784338283,
 'id': 'chatcmpl-e505a76e-c187-43c6-999c-c17df192c4d8',
 'model': '/Users/mwhipple/.cache/huggingface/hub/models--empero-ai--Qwythos-9B-Claude-Mythos-5-1M-GGUF/snapshots/5cebd89dd078b033c26988248740ddadf40f2fbd/Qwythos-9B-Claude-Mythos-5-1M-Q4_K_M.gguf',
 'object': 'chat.completion',
 'usage': {'completion_tokens': 18, 'prompt_tokens': 237, 'total_tokens': 255}}
#+end_example

*** Queue

**** Self-Improvement

The first actual practical goal as alluded to above is allowing the
agent to improve itself. To do so efficiently it should first be able
to read and then subsequently write to this file (on the local
filesystem).

**** Tools

Getting tools working is viewed as one of the highest priority items.
Tools are the most straightforward way to bridge models with things
outside fo their sandboxes, and presumably also forms the means for
many other typically expected agent behaviors (and may be the route I
pursue even if there are alternatives).

Working outside of a harness seems to make the interactions a bit
clearer, where the tool calls pass back through as messages to the
driving code/agent which is responsible for actually making the call
and returning the response.

I'm therefore expecting to produce a ToolBelt which both advertises
the tools to the model and can handle the tool call messages. One of
the big remaining questions is around the chat format and related
behavior encountered earlier.

**** Tidy Up Response Handling
The current code is sloppy but effective...without the need for
tighter integration this is a bit of hygiene but not pragmatically important.

**** Streaming

Streaming is ostensibly preferable to provide more realtime feedback,
but it introduces additional challenges in terms of needing to
reassemble some chunks. Basic streaming interaction is straightforward
and was done previously, but it seems wiser to defer leaning into
streaming until there is known working code that it can be used for
(for example getting all of the tool calling machinery working with
full messages before those messages get chunked up).
