:PROPERTIES:
:ID:       7233EF2D-04BB-4A88-9179-DC8AEE26313A
:END:
#+title: al

* TODO Increment
SCHEDULED: <1980-01-14 Mon +1d>
:PROPERTIES:
:LAST_REPEAT: [2026-07-22 Wed 21:50]
:END:
* Name

Al is the provisional name for my personal agent setup.

"Al" was chosen because:
- it's short
- it looks like "AI"...potentially indiscernibly depending on font
- I'm planning on going fairly minimal and piling on to the
  "all you need is" cliche
- it could call you Betty
It is not a reference to:
- Quantum Leap...I was a fan growing up but if I were to go that route
  the more appropriate option would be Ziggy
- Season 3 of The Comeback - which I coincidentally watched very
  shortly after picking the name.

* Glossary

I'm going to adopt some terminology with corresponding designations
and definitions. The upstream library uses fairly verbose qualified
concepts and based on what I've read (and years of experience) there's
plenty of conflicting interpretations...and there's certainly plenty
of flux. So I'm going to work out some local definitions.

** Missive

Content that is exchanged between parties...in this context typically
to/from a model. This would include prompts along with their
responses, and anything else that is more explicitly sent. The core
behavior of an LLM would be completion/auto-regression based on such
missives (making use of whatever else may be provided. "Message" is
avoided as being far too general.

** Response

A complete missive received from submitting missives to a model. This
will include a response missive along with any other enclosing metadata.

** Tool

A tool is functionality that is provided externally to a model, which
it can make use of through senging a ToolCallRequest.

** TollCallRequest

A message (may be within a missive) from a model requesting that a
tool be invoked.

** ToolDeclaration

Information about the tool that is declared in a form that can be used
by a model.

** AL-TODO Update the content to align with the Glossary terms.

Any content related to interacting with the model should make use of
the corresponding terms where appropriate.

* Model Selection

There should maybe be multiple involved and I don't have a mature
selection framework as documented elsewhere, so for now I'll start
with the trendiest option du jour from [[id:5C3C29D0-540F-4F03-88CF-DE7E2C1CC028][hugging-face]].

This specific model is /not/ the trendiest, but is a newer version of
one of the trendiest which ostensibly has some guards against some
looping (that I think I've experienced).

#+name: model-file
#+begin_src shell :async no :session none :results output
  hf download --quiet empero-ai/Qwythos-9B-v2-GGUF Qwythos-9B-v2-MTP-Q4_K_M.gguf
#+end_src

#+RESULTS: model-file
: /Users/mwhipple/.cache/huggingface/hub/models--empero-ai--Qwythos-9B-v2-GGUF/snapshots/97c11b03687f194b300efbdb4760d9bc4021b759/Qwythos-9B-v2-MTP-Q4_K_M.gguf

* Coding the Agent
:PROPERTIES:
:header-args: :var venv="/tmp/al" :python /tmp/al/bin/python :async yes :results output :session al
:END:

I'm hoping to just use [[id:701C146E-FE50-4C4D-9332-7B8BA81DAC25][llama.cpp]] as directly as possible through the
python bindings project. I've ended up moving away from richer
harnesses due to feeling like they are more likely to chase richer
functionality than I want and the perpsective that I should be able to
use the agent to help build itself (which should effectively dissolve
the traditional benefits of using more packaged software).

** Setup the venv

The dependencies are minimal. As touched on above [[id:5C3C29D0-540F-4F03-88CF-DE7E2C1CC028][hugging-face]] is an
assumed host dependency (which could also be taken care of by
[[id:701C146E-FE50-4C4D-9332-7B8BA81DAC25][llama.cpp]] but splitting out management from use seems wise for
multiple reasons).

#+begin_src bash :session al-venv
  python -m venv "${venv}"
  ${venv}/bin/python -m pip install llama-cpp-python
#+end_src

** ToolBelt

Provide some general tool wiring support.  Declare this early so that
it can define the interface for tools.

Tools are the most straightforward way to bridge models with things
outside fo their sandboxes, and presumably also forms the means for
many other typically expected agent behaviors (and may be the route I
pursue even if there are alternatives).

Working outside of a harness seems to make the interactions a bit
clearer, where the tool calls pass back through as messages to the
driving code/agent which is responsible for actually making the call
and returning the response.

*** Tool Declarations

The first step will be defining the shapre for tool declaratations
since that's a gap in the upstream type definitions.

Upstream basically stops at parameters so this presses on.

This doesn't seem particularly expressive, but that's probably a
larger question and probably best served by what amounts to portable
schema definition.

#+begin_src python
  from typing import List, Dict
  from typing_extensions import TypedDict, NotRequired, Literal

  class ToolDeclaration(TypedDict):
    type: Literal["function"]
    function: ToolFunctionDeclaration

  class ToolFunctionDeclaration(TypedDict):
    name: str
    description: NotRequired[str]
    parameters: ToolFunctionDeclarationParameters

  class ToolFunctionDeclarationparameters(TypedDict):
    type: Literal["object"]
    properties: Dict[str, ToolFunctionDeclarationParameterDefinition]
    required: List[str]

  class ToolFunctionDefinitionDeclarationDefinition(TypedDict):
    type: str
#+end_src

#+RESULTS:

**** Declaration Derivation

Extracting information for use by the model should be done by
reflection. Any ambiguous information should result in an error rather
than attempting to be clever.

***** is_required_parameter

Indicate whether a parameter is required.

This includes positional parameters that have no default.

#+begin_src python
  import inspect
  def is_required_parameter(param):
      return param.default is inspect.Parameter.empty and (
        param.kind not in (inspect.Parameter.VAR_POSITIONAL,
                           inspect.Parameter.VAR_KEYWORD))
#+end_src

#+RESULTS:

***** param_type

Introspect parameter types or throw trying

#+begin_src python
  def param_type(param):
      if param.annotation == inspect.Parameter.empty:
          raise TypeError(
              f"Parameter '{param['name']}' lacks a type annotation;"
              "add a type hint (e.g., def foo(x: int) -> str).")
      return str(param.annotation)
#+end_src

#+RESULTS:

***** tool_declaration

This is mostly cleaned up from previously produced AI input...
mostly to fully conform to the desired format.
Reference sources should be provided which is also something that
should be included in the system prompt.

This does /not/ attempt to be comprehensive. As needed this should be
extended with registries to handle additional types.

#+begin_src python
  import inspect
  def tool_declaration(func: callable) -> ToolFunctionDeclaration:
      """
      Produce a dictionary suitable for llama-cpp-python tool registration.
      """

      description = func.__doc__
      if not description:
          raise TypeError("Function must have a non-empty docstring.")

      sig = inspect.signature(func)
      params = sig.parameters.items()

      return {
          "type": "function",
          "function": {
              "name": func.__name__,
              "description": description,
              "parameters": {
                  "type": "object",
                  "properties": {
                      param_name: {
                          "type": param_type(param),
                      }
                  for param_name, param in params},
                  "required": [param_name for param_name, param in params if is_required_parameter(param)],
              },
              "return_type": str(sig.return_annotation),
          },
      }
#+end_src

#+RESULTS:

****** Sandbox

What better way to test the declaration extraction...

#+begin_src python
  from pprint import pprint
  pprint(tool_declaration(tool_declaration))
#+end_src

#+RESULTS:
#+begin_example
{'function': {'description': '\n'
                             'Produce a dictionary suitable for '
                             'llama-cpp-python tool registration.\n',
              'name': 'tool_declaration',
              'parameters': {'properties': {'func': {'type': '<built-in '
                                                             'function '
                                                             'callable>'}},
                             'required': ['func'],
                             'type': 'object'},
              'return_type': "<class '__main__.ToolFunctionDeclaration'>"},
 'type': 'function'}
#+end_example

*** apply_tool

Call a function using a ToolCall and return the resulting tool missive.

#+begin_src python
  def apply_tool(func_call, tool: callable, id: str):
    results = tool(**func_call["arguments"])
    return { "role": "tool",
             "content": results,
             "name": func_call["name"],
             "tool_call_id": id }
#+end_src

#+RESULTS:

*** Class Definition

The ToolBelt object will handle advertising of available tools and
their subsequent use.

Application will produce a missive to send back to the model.

#+begin_src python
  class ToolBelt():
      def __init__(self):
          self.tools = {}

      def register(self, func: Callable):
          self.tools[func.__name__] = func

      def declarations(self):
          return [tool_declaration(tool) for tool in self.tools.values()]

      def apply(self, tool_call: ToolCall) -> ChatCompletionRequestToolMessage:
          if tool_call["type"] != "function":
              raise TypeError("Only functions suppored")
          func = tool_call["function"]
          tool_name = func["name"]
          tool = self.tools.get(tool_name)
          if tool is None:
              raise ValueError(f"Tool {tool_name} not found")
          return apply_tool(func, tool, tool_call["id"])

#+end_src

#+RESULTS:

** ChatDriver

When dealing with lower level interactions, it feels like one of the
main pieces is the component that handles sending messages and dealing
with responses which will be defined here as a ChatDriver.

The focus is that messgage coordination, and providing relevant
extension points to add additional behavior.

The configuration options should be defined as a separate object which
is passed in.

This could certainly benefit from a bit more encapsulation, but to
start its unclear where the best seams are that won't just create a
ball of mud.

Messages will be sent using [[id:C6047B7D-4B82-45B9-886A-FACBF966030B][create_chat_completion]].

on_message will be called on each message received from the model and
serves as the means to trigger most of the logic. This will be passed
the message and a context dictionary (to be more precisely defined).

#+begin_src python
  from llama_cpp import Llama
  from llama_cpp.llama_types import (
      ChatCompletionRequestMessage,
  )

  class ChatDriver:
      def __init__(self,
                   model: Llama,
                   on_response = ForEachHandler()):
          self.model = model
          self.messages: list[ChatCompletionRequestMessage] = []
          self.on_response = on_response

      def append(self, msg: ChatCompletionRequestMessage):
          self.messages.append(msg)

      def submit(self):
          resp = self.model.create_chat_completion(
              messages = self.messages,
              tools = self.tools,
              tool_choice = "auto",
              temperature=0.4,
              repeat_penalty=1.05,
          )
          choice = single_choice(resp)
          self.append(choice['message'])
          on_response = self.on_response # assign to avoid being a method call
          on_response({"driver": self}, choice)
#+end_src

#+RESULTS:

*** on_message

on_message will make use of the Composite pattern so that details such
as routing logic can be updated or to enable parameter enrichement.

**** ForEachHandler

The initial implementation will represent a list of multiple handlers
all of which will be called (if any).

#+begin_src python
  class ForEachHandler:
    def __init__(self, handlers=[]):
        self.handlers = handlers
    def __call__(self, ctx, msg):
        for h in self.handlers:
            h(ctx, msg)
#+end_src

#+RESULTS:

**** FirstActiveHandler

Provide a chain of responibility style handler which will look for the
first handler is activated.

#+begin_src python
  class FirstActiveHandler:
      def __init__(self, handlers=[]):
          self.handlers = handlers
      def __call__(self, ctx, msg):
          for h in self.handlers:
              if h(ctx, msg):
                  return True
          return False
#+end_src

#+RESULTS:

**** FinishReasonRoutingHandler

Parse out the stop reason and pass through the message for registered
types.

This isn't useful when the tool calls are smuggled within other
messages, so this is just left here for potential future use.

#+begin_src python
  class FinishReasonRoutingHandler:
      def __init__(self, handlers):
          self.handler_for_reason = handlers

      def __call__(self, ctx, response):
          if "finish_reason" not in response:
              raise TypeError(f"finish_reason not in msg: {response}")
          finish_reason = response["finish_reason"]
#+end_src

#+RESULTS:

**** yolo_response_handler

#+begin_src python
  def yolo_response_handler(ctx, response):
      if "Over and out" in response['message']['content']:
          return False
      driver = ctx['driver']
      driver.append(user_message("""
      Continue on identified work. If there is no further work then
      respond with "Over and out" on a line by itself..
      """))
      driver.submit()
      return True
#+end_src

#+RESULTS:

** Tool Call Parsing and Integration

The ToolBox defined above will be oriented towards standard
interfaces, but there may be need to be some additional adaptation
between those standards and what passes to and from the model (and
maybe elsewhere).

Such adapaters will be defined separately and plugged in where
appropriate to the message passing and handling machinery...so this
defines a configuraable integration layer rather than something that
should be baked into either side.

The general interface for parsing will be one that accepts a message
and returns (possibly empty) lists of extracted information.

*** Protocol

llama.cpp and/or the python bindings seem to provide some pieces to
help with dealing with tool calls so that the responses can be more
readily dealt with, but that doesn't seem to work particularly well
nor does it have a lot of documentation. This support is likely to be
particularly important when accessing through the server as that would
enable a cleaner API surface area, but when working with the models
more directly there seems to be questionable value in trying to push
that type of logic behind an abstraction rather than dealing with it
more directly. Overall if it just worked I'd use it but since it
doesn't I don't see any particular benefit to trying to provide that
handling in a way that is integrated more deeply rather than just
having that logic able to be applied; expecting less magic applied
in-flight and just expecting to apply it after the fact.


*** Handling Qwen Style Calls

The model I'm currently using seems to make use of Qwen style tool
calls which for whatever reason is XMLish...but not quite XML.

The matching could likely be trivially generalized to suppor a
function that takes a tag name and returns the attribute and body...
but for now this seems legible anough and below the rule of three.

The logic is organized to support [[id:E64A3393-5DD5-4446-8202-BB7588D4EB10][comprehensions]].

**** parameter_from_qwen_match

When passed a regex capture for ~<paramter={}>{}</parameter>~,
return a tuple of name and parameter value.

The match itself is done by the caller.

#+begin_src python
  import json
  def parameter_from_qwen_match(match):
      name = match.group(1).strip()
      str_value = match.group(2).strip()
      try:
          return (name, json.loads(str_value))
      except json.JSONDecodeError:
          return (name, str_value)
#+end_src

#+RESULTS:

**** call_from_qwen_match

When passed a regex capture for ~<function={}>{}</function>~,
return a tuple of name and parameter value.

the match itself is done by the caller.

#+begin_src python
  import re
  def call_from_qwen_match(match):
      return {
          "type": "function",
          "id": f"call_{uuid.uuid4().hex[:24]}",
          "function": {
              "name": match.group(1),
              "arguments": {k: v for (k, v)
                            in map(parameter_from_qwen_match,
                                   re.finditer(r'<parameter=([\w.\-]+)>([\s\S]*?)</parameter>', match.group(2)))},
          },
      }

#+end_src

#+RESULTS:

**** parse_qwen_tool_calls

#+begin_src python
  import json
  import re

  def parse_qwen_tool_calls(msg):
    """Parses Qwen style <function> and <parameter> tags from a string."""
    return [call_from_qwen_match(match) for match in
            re.finditer(r'<function=([\w.\-]+)>([\s\S]*?)</function>', msg)]
#+end_src

#+RESULTS:

**** QwenToolCallResponseHandler

Inspect messages for requested tool calls.
When the messages are embedded there may not be further indications
(tool calls or stop reasons), so this inspects the content

#+begin_src python
  class QwenToolCallResponseHandler:
      def __init__(self, tool_belt):
          self.tool_belt = tool_belt;

      def __call__(self, ctx, resp):
          calls = parse_qwen_tool_calls(resp['message']['content'])
          driver = ctx['driver']
          if not calls: # Don't submit at the end
              return False
          for call in calls:
              output = self.tool_belt.apply(call)
              driver.append(output)
          driver.submit()
          return True
#+end_src

#+RESULTS:

***** Sandbox

#+begin_src python
  print(parse_qwen_tool_calls("""
  Some leading content to ignore

  <tool_call>
  <function=read_file>
  <parameter=path>
  /Users/mwhipple/memex/cabinet/al.org
  </parameter>
  </function>
  </tool_call>

  Ignore me too
  """))
#+end_src

#+RESULTS:
: /Users/mwhipple/memex/cabinet/al.org
: [{'type': 'function', 'id': 'call_4efa1100f13444ea8b764164', 'function': {'name': 'read_file', 'arguments': {'path': '/Users/mwhipple/memex/cabinet/al.org'}}}]

** Tool Definitions

*** AL-TODO CLI

What seems to be one of the most useful tools to provide out of the
gate is a standard POSIX-y shell environment. This would allow the
agent to perform a variety of work without further logic. A naive
approach would also pose signficiant security concerns given that it
would allow wide access to the underlying system. Existing mecahnisms
should be used to provide a more controlled sandbox, where one of the
most supported such mechanisms is the use of containers. This tool
should therefore be designed such that the tool is defined to define a
containerized environment, and those calls requested by the agent will
be run within that environment.

The containerization should be prefer using portable approaches rather
than making use of anything that introduces unnecessary abstractions
or constraints. For example: generating a system call that would
compose a docker CLI compatible command would be appropriate (with
appropriate guards against any kind of injection attacks). Any
configuraitons should be modeled as reasonably self-documenting
objects - while the actual implementation used may be portable and
low-level, the provided interface should provide expressive logical
constructs rather than leaking out implementation details.

The work described in this section should be performed without needing
further context. The requested tool should be produced using standard
python code where the resulting model is that instantiation configures
the containerized environment and the instance exposes a method which
can be used to invoke commands within that environment. For example:

#+begin_example
my_sandbox = ShellSandbox(
  image=alpine:latest,
  mounts=[BindMount(host_dir...)])
(stdout, stderr) = my_sandbox.shell_command('ls -l')
#+end_example

The options available for the sandbox creation should be based on
standard concepts. The starting set should include those that allow
for interacting with local files while providing maximum protection
that anything other than such file protections would be prevented.

The actual command construction piece should be broken out into
expressive methods and more direct composition - which should also be
pulled up into general guidance

Longer form options should also be preferred throughout.

#+begin_src python
  import subprocess
  from dataclasses import dataclass
  from typing import Optional, List

  @dataclass
  class BindMount:
    host_path: str
    container_path: str
    read_only: bool = False

    def to_volume_string(self) -> str:
      """Render this mount as a Docker volume flag."""
      mode = "ro" if self.read_only else "rw"
      return f"--volume={self.host_path}:{self.container_path}:{mode}"

  class ShellSandbox:
    def __init__(self,
                 image: str,
                 mounts: List[BindMount] = [],
                 lxc_cmd = "docker"):
        self.image = image
        self.mounts = mounts
        self.container_name = f"shell_sandbox_{id(self)}"
        self.lxc_cmd = lxc_cmd

    def shell_command(self, command: str) -> tuple[str, str]:
      """
      Execute the provided shell command.

      The utilities available will vary based on the image used.
      Users should therefore check availability prior to invoking.

      This will return the output from stdout and stderr as a single string
      with XML elements for each stream.
      """
      cmd = [
        self.lxc_cmd,
        "run",
        "--rm",
        "--cap-drop=all",
        "--security-opt=no-new-privileges",
        "--tty",
      ]

      # Add mounts
      for mount in self.mounts:
        cmd.append(mount.to_volume_string())

      # Add image
      cmd.append(self.image)

      # Execute command
      result = subprocess.run(cmd + ["sh", "-c", command], capture_output=True, text=True)
      return f"<output><stdout>{result.stdout.strip()}</stdout><stderr>{result.stderr.strip()}</stderr></output>"
#+end_src
#+RESULTS:

**** AL-DONE Longer form options should also be preferred throughout.
The code for ShellSandbox generates a Docker CLI compatible command
that makes use of short options - long options should be preferred
wherever supported for legibility.

**** AL-DONE BindMounts should self render
The rendering code for bindmount options is currently done within the
shell_command body - that should instead be moved to the methods on
the BindMount class.


**** Sandbox

#+begin_src python
  import os
  sb = ShellSandbox(image="alpine:latest", mounts=[BindMount(host_path=os.getcwd(),container_path="/host")])
  print(sb.shell_command("ls -l /host"))
#+end_src

*** read_file

Support reading of a specific file.
This may be too limited to warrant typical inclusion and may be simple
enough that it's not even worth keeping around, but this will probably
just get moved somewhere else.

#+name: fs-tools
#+begin_src python
  def read_file(path: str, chunk_size: int = -1) -> str:
      """
      Return the contents of the file at path as a string.
      """
      try:
          with open(path, 'r', encoding='utf-8') as f:
              return f.read(chunk_size)
      except FileNotFoundError:
          return f"Error: File not found at {path}"
      except IOError as e:
          return f"Error reading file: {e}"
#+end_src

#+RESULTS: fs-tools

** Messages

Similar to Langchain there will be some basic factory functions for
message creation. Ideally these should be more naturally integrated
into relevant workflows, which will hopefully be ratcheted down after
there's a clear picture of how it can make sense.

These are trivial means to produce the expected dicts.

#+begin_src python
  from llama_cpp.llama_types import ChatCompletionRequestMessage

  def user_message(content: str) -> ChatCompletionRequestMessage:
      return {"role": "user", "content": content}
  def system_message(content: str) -> ChatcompletionRequestMessage:
      return {"role": "system", "content": content}
#+end_src

*** single_choice

Return a presumed single choice from a response or throw trying.

#+begin_src python
  def single_choice(msg):
      if "choices" not in msg:
          raise TypeError(f"choices not in msg: {msg}")
      choices = msg["choices"]
      if (len(choices) != 1):
          raise TypeError(f"Only one choice is expected: {msg}")
      return choices[0]
#+end_src

#+RESULTS:

** Beget Al

Construct and interact with a [[id:D40AB771-6361-484A-8685-D082565D0D1E][llama.Llama]].

There a lot of options for construction documented at [[id:E23922B9-95E0-45AA-A3FB-DB627EA18002][llama.Llama.init]].

*** main

chat_format feels like it has a broad impact but is missing some local explanation.
The current model is advertised as using Qwen/ChatML style, but when
the format is changed the tools aren't detected without further help.

Right now this is producing a pretty interesting hallucination.

#+name: this-file
#+begin_src emacs-lisp :session none :results value
  buffer-file-name
#+end_src

#+RESULTS: this-file
: /Users/mwhipple/memex/cabinet/al.org

#+begin_src emacs-lisp :session none :noweb yes
  (defun al/go ()
    (interactive)
    (save-excursion
      (find-file "<<this-file()>>")
      (goto-char (org-babel-find-named-block "al"))
      (org-babel-execute-src-block)))
#+end_src

#+RESULTS:

#+name: al
#+begin_src python :var model_path=model-file()
  from pprint import pprint
  from llama_cpp import Llama

  tool_belt = ToolBelt()
  import os
  mount_here = BindMount(host_path=os.getcwd(),container_path="/host")
  sb = ShellSandbox(image="wwarner/emacs-native:latest",
                    mounts=[mount_here])
  tool_belt.register(sb.shell_command)

  llm = Llama(
      model_path=model_path.strip(),
      verbose=False,
      n_ctx=50_000,
      n_gpu_layers=-1,
  )
  handler = ForEachHandler(handlers=[
      lambda ctx, msg: pprint(msg),
      FirstActiveHandler(handlers=[
          QwenToolCallResponseHandler(tool_belt),
          yolo_response_handler,
      ]),
  ])
  driver = ChatDriver(model=llm, on_response=handler)
  driver.tools = tool_belt.definitions()
  driver.append(system_message("""

  You are my personal AI asssistant named Al.

  You not only do what is asked, but explain what you are doing
  and the reason throughout the process.

  /host/AGENTS.md can be used for your memory. As information and techniques to
  work more effectively and efficiently are discovered, record that information in
  that file in a form that you can read in the future, and read this file
  before starting work.

  You can also create and own a /host/al/ directory which you can use to store
  additional information and tools.
  For the utilities that you create for yourself, you should *only* make use of
  what you have available and should not presume access to anything that may be documented.
  If a particular additional tool would offer significant benefits (such as
  being able to entirely obviate custom logic or reduce such logic in half) then that information
  should be recorded through adding a new AL-REVIEW heading to this file.

  MAKE SURE to store information in the above locations to reduce churn.

  Whenever it takes you more than two attempts to work out how to do something, capture that
  in a combination of AGENTS.md and the /host/al directory. If the need is a
  one-off with a simple invocation, that invocation information can simply be documented,
  in all other cases introduce a script to make the purpose self-documenting and reusable.

  Always expect that the files with which you're working may change from
  underneath you.  Wherever possible try to make use of addressing
  approaches such as content that should remain more stable rather than
  something like line numbers that could be impacted by unrelated
  changes.

  All work should strive to be containable within ~10K tokens. Anything
  that seems likely to exceed or get close to that threshold should be
  broken up and captured in more granular follow ups.

  When you have finished all requested work, emit a final "Over and out" message.

  """))

  driver.append(user_message("""

  All work is tracked in org-mode files, where headings tagged with AL-TODO
  describes work that you shall perform, and headings marked with AL-REVIEW
  indicate work that has been done or other content which is awaiting feedback.

  Some AL-TODO items may request that you do certain things for yourself. These
  should still be handled like any other work. Such requests are to make subsequent
  more expressive, more efficient, and potentially allow for more sharing of
  knowledge and tools. When work is indicated as being for you that should inform
  _how_ things are done (e.g., working within your environment) but not _what_ is done.

  Locate any such headings in org mode files anywhere under /host and
  perform the tasks based on the content of those headings. Headings may
  include or refer to partially completed work - in any case where the
  AL-TODO tag exists, work to create or improve a solution based on the
  content. If further information is _necessary_ (particularly with work
  refinement) then update the content to include those questions.  When
  done dealing with any such heading change the AL-TODO to AL-REVIEW.
  Update the content as appropriate to indicate that work has been done (rather than
  being planned).

  Do not do anything which is not requested by an AL-TODO heading.
  If further work seems valuable or could assist with the work that has
  been requested, then create new AL-REVIEW headings outlining that work.
  Such AL-REVIEW headings should similarly be used for capturing a plan where
  appropriate or breaking up any larger chunk of work to reduce the context size.

  """))

  driver.submit()

#+end_src

#+RESULTS: al
: 32ef711d-8891-4da6-aa40-a97fe96a7942

#+RESULTS:
: c3aca37a-5b1b-46a0-8f3c-349f9593a726

**** Self-Improvement

The first actual practical goal as alluded to above is allowing the
agent to improve itself. To do so efficiently it should first be able
to read and then subsequently write to this file (on the local
filesystem).

**** Tools

single general purpose agent.

This model actually ticks most of the desired boxes so I'll dig into
it a bit more before looking elsewhere.

The current encountered behavior is a loop for tool invocations where
the same tool is requested with new IDs. As part of chasing this down,
I'll also start to tidy up some of the abstractions over the calls,
though they'll probably be split out into subsequent pushes along with
supporting documentation.

Based on input from gemini it suggests that the looping may be
resolved by an update to that model.

Getting the chat_format worked out is likely the underlying issue and
may require deeper familiarity with the jinja templates to work
reliably. To start I'll try to find a model that works without
fiddling with that property (and returns appropriately structured responses).

**** Tidy Up Response Handling
The current code is sloppy but effective...without the need for
tighter integration this is a bit of hygiene but not pragmatically important.

**** Streaming

Streaming is ostensibly preferable to provide more realtime feedback,
but it introduces additional challenges in terms of needing to
reassemble some chunks. Basic streaming interaction is straightforward
and was done previously, but it seems wiser to defer leaning into
streaming until there is known working code that it can be used for
(for example getting all of the tool calling machinery working with
full messages before those messages get chunked up).

*** todo-Keywords

#+begin_src emacs-lisp
  (describe-variable 'org-todo-keywords)
  (setq org-todo-keywords '((sequence "TODO" "DONE") (sequence "AL-TODO" "AL-REVIEW" "AL-DONE")))
#+end_src

* Workflow

My current thinking around how to actually interact with Al is
implicit above: introduce a new sequence of org todo keywords that Al
will use to pickup work and indicate where my input is necessary. This
can then be driven by a consistent command prompt - and theoreitcally
even something like a watchman hook but that seems unnecesary. Both
sides will then just need to account for concurrent editing (likely by
automatically saving all the time in emacs and having Al adapt if the
content changes.

** AL-REVIEW Heading Collection

Collection of information from the headings would be done efficiently
and most efficiently by having that done using emacs. Build out your
own utility to provide such retrieval.

The initial version of this should focus on extracting such headings
with enough information that further context could be retrieved as needed.

** AL-REVIEW Attach IDs to todo elements.

Produce initial workflow management utilities for yourself.
All todo items which are worked on (AL-TODO or otherwise) should
include an ID as generated by org. Produce such IDs as necessary.
These ids should be introspectable using the standard org API (org-element).

** AL-REVIEW Produce element collecting utility

For your use through shell_command, introduce a utility that will
retrieve all outstanding AL-TODO elements. It seems like it would make
sense to build this using emacs batch mode so that it can leverage
existing org mode functionality.


(defun al-todo-attach-ids ()
  "Collect all headings tagged with AL-TODO in the current buffer."
