:PROPERTIES:
:ID:       0F78767D-42FF-4027-B3A2-26CA1898F788
:END:
#+title: obi

* TODO Iterate
SCHEDULED: <1980-01-11 Fri +1d>
** Work through [[id:D5B6CBC5-AB99-4278-A8A3-ACB9124B68F4][obi/describe-function]]

* Background

~obi~ is what I'm calling my effort to rethink what a user
interface/IDE looks like in a world with AI, as contemplated in
[[id:3FA03B7E-EC84-40E0-AB18-E3AED640DA89][scrapbook-interface]].

It's starting off being implemented within emacs, and the name and
genesis will start with building on top of [[id:04B03591-50E7-41E2-A2A5-0C2893FAD39C][org-babel]] (which is also
the source of the name), but after starting down this road two
goals enjoin me to split out the effort a bit more:

- clearer interfaces could decouple the system from emacs
- the core interface elements should be flipped around

Emacs, like many other editors, leans into the notion that a given
view and the editor itself provides specific behavior, but an
extension to the proposed model is that such behavior should instead
be pushed into the content. This is likely to drift closer to
alternative editors like Acme. The underlying motivation here is to
reduce the surface area of the exposed interface, and to make shift
towards a model where the content model has primacy rather than
prospectively being subordinated to the editor model.

** Design Principles

Much standard emacs behavior is very oriented towards contextual
behaviors and corresponding implicit parameters. Functions operate
based on editor state, and make frequent use of editor provided
constructs. As part of flipping the ownership around, much of that
will be encoded more directly. The content model will be able to provide
references to itself, but such references should be passed more
explicitly into the logic.

** Compared to Org-Babel

The general model will begin as /very/ similar to org-babel, and will
steal much of the underlying logic. Logic can be invoked by having
functionality embedded within content which can be invoked and the
results rendered. The expected differences are that that mechanism
will be more clearly and uniformly defined, and some of the behavioral
variations will be removed: each such invocation will produce a common
results object which will have references to all produced outputs and
which will be populated asynchronously. This interface will then also
be extended to support virtually all use cases. Behaviors that may
currently be provided by specialized modes (for example something like
magit) could then be replaced by a file template.

Another significant change is that this will likely gravitate towards
defining more of a DAG (directed acyclic graph): so rather than having
the interaction model primarily defined as executable blocks which
produce outputs, it will be defined as blocks which can be defined as
the expressions evaluated from other blocks (thereby providing a
simpler means for capturing multiple outputs).

** Compared to Spreadsheets

A belated realization for some of the DAG ideas mentioned above is
that it also produces a system which is similar to a
spreadsheet...where those blocks defined as expressions are a
generalization of spreadsheet cells containing formulas.

Without more substance this comparison doesn't have much practical
benefit, but the popularity of spreadsheets along with the idea
that that type of model is still called out as exemplary (such as in
DDIA) supports that this line of thought may have some merit.

** Function Syntax

One of the underlying goals as outlined in [[id:3FA03B7E-EC84-40E0-AB18-E3AED640DA89][scrapbook-interface]] is that
this should biased towards supporting a range of what amounts to IPC
rather than trying to control it. As org-babel behaves, the goal
should be that functions can be defined using whatever syntax and
tools make sense, and the system provides the wiring to support those
different types.

** Envelopes

The interface between the notebooks and the invoked commands should
have a contained definition and therefore requires support for some
type of consistent envelope, rather than expecting the system to deal with
variations. This should in particular reflect what amounts to a
basic protocol level detail rather than having any implication on the
data itself (continuing from the goals outlined for the Function
Syntax. This should support what amounts to dispatching but /not/
limit what is on the other end of that dispatching. For example if a
function call is expected to produce 3 streams then the envelope
should allow for discovery of those streams so that logic can be
applied to them...but the content of those streams would remain
a specialized detail - this most clearly reflects support for things
like stdout/stderr, and also the goal of surfacing what is actually
being done and similar logging concerns.

Initially this will probably simply be represented in lisp sexps using
alists or plists, but what is provided should be small and simple
enough that it could be readily replaced with something else like JSON
or Protobufs.

* Introspection

Much of how this will work will be built on top of the document model,
where emacs generally and org-mode in particular seems more oriented
towards providing logic rather than deifning such a model. One of my
first tasks will therefore be to extract and repackage the underlying
model.

** Content Selection

In the longer term I'd gravitate towards something like XPath
selection, but that will be incremental as needed, starting with what
is there.

*** obi/block-named
:PROPERTIES:
:ID:       546AA76D-E686-4D85-BE25-B231678285ED
:END:

[[id:04B03591-50E7-41E2-A2A5-0C2893FAD39C][org-babel]] seems to gravitate towards using names as the means to
identify/reference blocks, so that will be what is started with.
This is provided by [[id:5E5ACC40-83BE-4934-BA1B-01FECE80BBED][org-babel-find-named-block]] which simply needs some
packaging up to be less mutate-y.

#+begin_src emacs-lisp
  (defun obi/block-named (name)
    "Find the block with the provided NAME or null if it cannot be found."
    (when-let* ((start (org-babel-find-named-block name)))
      (save-excursion
        (goto-char start)
        (org-element-at-point))))
#+end_src

#+RESULTS:
: obi/block-named

** Initial Work

- [[id:1D039937-F8B4-423A-A732-20E8CDDE4BB7][obi/agenda]]

* Old Info

** Background

One of the other fairly significant goals is that while I'll be using
obi with org-babel and emacs for the foreseeable future, I'd also want
that to be detachable. Therefore everything should remain fully
transparent so that what is done could be readily extracted to some
other interface like a boring old shell.

Beyond babel and evident alternatives like Jupyter, I'm also likely to
want to draw on ideas from other systems that had interfaces similar
to interactive notebooks such as the Acme editor and Oberon.

** Initial Design Ideas

All execution should default to asynchronous evaluation.
Basic async execution can likely be handled by splitting out the
overall flow, but a further goal would be consistently exposing what
is being done which will be hidden if things are being done directly
in emacs-lisp/system calls, so using something like comint extensively
to allow discovery of the invoked commands will be pursued.

* TODO obi/execute-src-block
:PROPERTIES:
:ID:       31893E0D-17BB-4DE7-8C4D-9D98E2D23856
:END:

Splitting up [[id:D7816316-280D-4B7B-9420-3E33264E24D2][org-babel-execute-src-block]]

I'll start by just expecting to break up what is there.

** executor-type

Split out executor selection as it's a bit wordy for a let block.

Return any explicitly provided value, otherwise detect based on the
next character if it exists.

It seems like this may just be doing too much...maybe I want to split
out functions?
Within this function it looks like this is only used to produce a message?

Rather than decomposing this function maybe the first pass will be to
attempt to gut it...

** Cut to execute

Inferring from past experience that the specialized logic lives in the
~org:babel-execute:<lang>~ bodies leads me to zero in on that
logic. That needs "lang" which is extracted from "info". The first few
lets are therefore used.

** should evaluate

One variable that seems worth trying to get a handle on is whether
things will be evaluated. This is typically going to amount to whether
some functionality gets applied and would therefore seem most clearly
modeled as something equivalent to multiple phases where evaluation is
an optional phase, but it is currently handled as flags.

To start we'll assume that this will be checked outside of the function

** body

** obi/BlockParams

Support working with parameters for a block.  This provides a closure
over the parameters, returning a function which can be called with a
parameter name/keword to return the value of that parameter.

#+begin_src emacs-lisp
  (defun obi/BlockParams (bp)
    (lambda (sym) (cdr (assq sym bp))))
#+end_src

#+RESULTS:
: obi/BlockParams
** obi/execute-src-block

This function collects the context which results in an ~info~ object
that is then used to perform the actual execution.

It looks like the key piece to make this a bit more supple is
[[id:D9D6DA14-C18F-43AD-A16B-7C9E1E6E9782][org-babel-insert-result]], where if we break this up to support async
flows then that should be trigged by the callback.

Unfortunately [[id:D9D6DA14-C18F-43AD-A16B-7C9E1E6E9782][org-babel-insert-result]] is also pretty sprawling and
should be broken up.

#+begin_src emacs-lisp
  (defun obi/execute-src-block (&optional arg info params executor-type)
    "Execute the current source code block and return the result.
  Insert the results of execution into the buffer.  Source code
  execution and the collection and formatting of results can be
  controlled through a variety of header arguments.

  With prefix argument ARG, force re-execution even if an existing
  result cached in the buffer would otherwise have been returned.

  Optionally supply a value for INFO in the form returned by
  `org-babel-get-src-block-info'.

  Optionally supply a value for PARAMS which will be merged with
  the header arguments specified at the front of the source code
  block."
    (interactive)
    (let* ((org-babel-current-src-block-location
            (or org-babel-current-src-block-location
                (nth 5 info)
                (org-babel-where-is-src-block-head)))
  	 (element (org-element-context))
           (info (if info (copy-tree info) (org-babel-get-src-block-info nil element)))
  	 (result-params (cdr (assq :result-params params)))
  	 (exec-start-time (current-time))
  	 (exec-result (obi/exec-result-for-info info)))
      (unless (member "none" result-params)
        (org-babel-insert-result
         exec-result result-params info
         (when (member "replace" result-params) new-hash)
         lang
         (time-subtract (current-time) exec-start-time)))
      (run-hooks 'org-babel-after-execute-hook)
      exec-result))

#+end_src

#+RESULTS:
: obi/execute-src-block

** obi/exec-result-for-info

~info~ is the object that holds all of the important info (and could be
extended as needed), so let's use that to drive the actual execution.

#+begin_src emacs-lisp
  (defun obi/exec-result-for-info (info)
    (let* ((body (org-babel--expand-body info))
    	 (lang (nth 0 info))
    	 (params (nth 2 info))
    	 (cmd (intern (concat "org-babel-execute:" lang)))
    	 (result-params (cdr (assq :result-params params)))
  	 (maybe-wrapped
  	  (lambda (r)
  	    (let ((wants-value? (eq (cdr (assq :result-type params)) 'value))
  		  (wants-collection? (or (member "vector" result-params) (member "table" result-params))))
  	      (if (and wants-value? wants-collection? (not (listp r)))
  		  (list (list r))
  		r)))))
      (unless (fboundp cmd)
        (error "No org-babel-execute function for %s!" lang))
      (let ((exec-result (funcall maybe-wrapped (save-excursion (funcall cmd body params)))))
        exec-result)))
#+end_src

#+RESULTS:
: obi/exec-result-for-info

** Test Element

#+begin_src emacs-lisp
  "foo"
#+end_src

#+RESULTS:
: foo

** obi/insert-result

Start to split up [[id:D9D6DA14-C18F-43AD-A16B-7C9E1E6E9782][org-babel-insert-result]].

Perform some basic result filtering...also includes file handling
which should likely be split out a bit more.

#+begin_src emacs-lisp
  (cond ((stringp result)
	 (setq result (substring-no-properties result))
	 (when (member "file" result-params)
	   (setq result
                 (org-babel-result-to-file
		  result
		  (org-babel--file-desc (nth 2 info) result)
                  'attachment))))
	((listp result))
	(t (setq result (format "%S" result))))

#+end_src


* Notes

Splitting out a closure over params seems potentially helpful...
May not be any terser in emacs-lisp though.

* Library

** Help

*** obi/describe-function
:PROPERTIES:
:ID:       D5B6CBC5-AB99-4278-A8A3-ACB9124B68F4
:END:

#+name: obi/describe-function
#+begin_src emacs-lisp :var function="MISSING"
  (describe-function (intern-soft function))
#+end_src

**** Queue
Avoid additional buffer
Render with text properties


