:PROPERTIES:
:ID:       22E2131D-5ADF-46AD-BEBB-8A5745CBA94F
:END:
#+title: meta

A notebook for this project itself.

This project is called a "cabinet" which is a reference to a physical
zettelkasten setup which is likely to involve a card cabinet, and this
project uses org-roam to provide that model

* Project Structure

The project primarily consists of a top-level listing of directories,
where each directory houses a particular topic (which may be a
project). Each directory will contain an index.org file which serves
as the landing page for that topic, and any additional source or
generated files for the topic.

** ID Links

Links to UUIDs refence the sections with those IDs. These can be efficiently
discovered using org-roam, but outside of org and until an alternative interface
to that database is provided, approaches such as grep can be used to locate
the destination.

** Composed Documents

Many of the documents will be composed using transclusion.
This allows the referenced files to provide a smaller context,
reduce the likelihood of editing collisions, and be easier to work with.

For any non-trivial topic, the index.org file will be composed of other
notebooks within the directory.

*** Transclusion vs. Tangling (for Source)

The wider project will make use of a combination of tranclusion (to embed
an external file within a notebook) and tangling (to produce external files
from a notebook; these effectively amount to supporting the information
flowing in both directions (transclusion flows into notebooks, tangling out).

Notebooks should contain all /source/ and that should guide when to
use which approach. If any file or information (or its equivalent)
should be able to be reproduced by evaluating the content of the notebook,
then it is not source and should be transcluded. If information is present
in content which is not clearly captured elsewhere in the notebook, then it
should be included in the notebook and tangled.

In terms of AI-assisted work, this should lend itself to a model where
specifications and information acting as prompts should be captured in the
notebook, whereas what is produced from that information can be transcluded.

** Self-Contained

The information within this space should be self-contained and should evolve as needed.
Rather than presuming constant connectivity it should be conducive to working in
an offline mode.

*** Using Help

Working with available resources should always be the initial preference. This should
include making use of any available help facilities. Whenever such information is used
it should be captured for future reference in an appropriate topic. In cases where
the help provides the necessary information, this should be handled by a flow such as:

- Create/find notebook content which invokes a help command producing relevant information
- As necessary, update that notebook to transclude that information
- Include a reference to that notebook content where it was used

*** Capturing Usage

When provided help is not immediately clear for any reason, produce clarifying notebook
content which more clearly demonstrates the behaviors.

*** External References

When information is not locally available (or to help bootstrap that local availability),
references to external sources should be included. This should be complemented by capturing
necessary information locally, in a form similar to Capturing Usage above. The end result of
this should be to support self-containment/offline usage, but should **not** extend to
reproducing all of the external information. Only that information which is directly relevant
to what is needed should be captured locally, and any further clarifying information should
be referenced but not duplicated.

** Exemplars

The following folders follow the desired structure:
- [[file:ai_models/][ai_models]]
- [[file:al][al]]
