:PROPERTIES:
:ID:       0DC5A06B-8D69-4CC4-AA03-009E55BFEDCF
:END:
#+title: scrap
* Overview

scrap is what I'm calling my set of of utilities for working with
literate programming style notebooks, as described in
[[id:3FA03B7E-EC84-40E0-AB18-E3AED640DA89][scrapbook-interface]].

Most of these are expected to be Haskell programs written on top of
Pandoc.

** Why Haskell?

Pandoc itself is written in haskell, but has very nice support for
building on top of it in other languages, most notably (but not
limited to) Python and Lua. There are several factors that went into
using haskell.

*** Squishy Factors

Using the /same/ language avoids the need to any type of translation
across the bindings and makes reading the code throughout more
seamless.

Subjectively a lot of the logic that needs to be written can be very
naturally represented with pattern matching, which is more naturally
supported in haskell than in either python or lua.

Aspirationally I also think that if AI is used for coding then we
should move towards languages that may be more difficult or onerous to
write but provide stronger guarantees. Given that the AI should absorb
the actual cost of writing, this can provide a means to have higher
confidence in the result - particularly if there are means to provide
formal verification (which outside of the pandoc variable would push
me towards Idris).

*** Concrete Factor

The primary deciding factor is based on past experience. I've built
out functionality on top of pandoc a few times in the past and have
generally gravitated towards lua given that it is not only more
accessible to most developers than haskell, but it also has a built-in
interpreter (and therefore virtually no additional environmental
setup).

Lua extensions work very well...but in one of the less trivial
projects where I have such a setup one nuisance is lack of build-time
guarantees. When working with something like pandoc there is a subset
of behavior that may be of interest at a given time, but the code
needs to handle all of it. I'd therefore run into belated feedback
when something I hadn't cared about (and therefore hadn't
specified/tested) would fail at runtime at some point in the future
due to some proximal change knocking something loose. Having live
specifications can protect against that while also providing helpful
documentation (the referenced project makes heavy use of BATS for
tests), but having stronger guarantees throughout the process seems
more economical - particularly for more personal projects where
comprehensive documentation/specification may otherwise be overkill.

* [[file:book.org][book]]
#+transclude: [[file:book.org][book]] :level 2

* [[file:tangle.org][tangle]]
#+transclude: [[file:tangle.org][tangle]] :level 2
