:PROPERTIES:
:ID:       D65CCEA0-A995-4F16-8E3E-E3FDCDF58170
:END:
#+title: al/background
* Plans
First and foremost I'd want most of this work to be able to be driven
empirically which requires a harness to collect and refine some of the
underlying processes. I'll look at pulling from existing solutions
such as DSPy, but unfortunately much of what exists requires a server.
* Name
Al is the provisional name for my personal agent setup.

"Al" was chosen because:
- it's short
- it looks like "AI"...potentially indiscernibly depending on font
- I'm planning on going fairly minimal and piling on to the
  "all you need is" cliche
- it could call you Betty
It is not a reference to:
- Quantum Leap...I was a fan growing up but if I were to go that route
  the more appropriate option would be Ziggy
- Season 3 of The Comeback - which I coincidentally watched very
  shortly after picking the name.
* Glossary
I'm going to adopt some terminology with corresponding designations
and definitions. The upstream library uses fairly verbose qualified
concepts and based on what I've read (and years of experience) there's
plenty of conflicting interpretations...and there's certainly plenty
of flux. So I'm going to work out some local definitions.
** Missive
Content that is exchanged between parties...in this context typically
to/from a model. This would include prompts along with their
responses, and anything else that is more explicitly sent. The core
behavior of an LLM would be completion/auto-regression based on such
missives (making use of whatever else may be provided. "Message" is
avoided as being far too general.

Message will still be in use in the general sense and in forms
inherited from upstream.
*** Retained Missive
A missive which is retained to become part of the context.
*** Transient Missive
A missive which is issued, but not stored as part of the context.
** Response
A complete missive received from submitting missives to a model. This
will include a response missive along with any other enclosing metadata.
** Tool
A tool is functionality that is provided externally to a model, which
it can make use of through senging a ToolCallRequest.
** TollCallRequest
A message (may be within a missive) from a model requesting that a
tool be invoked.
** ToolDeclaration
Information about the tool that is declared in a form that can be used
by a model.
* Error Handling
Presumably standard practice, but captured here for my own and Al's sake:
errors should typically be converted into values that are more informative
than exceptional. This will often be contrary to typical practice of failing
early and loudly (and avoiding trying to be clever).

Often the AI can adapt around errors and therefore surfacing them as
information rather than failures can guide follow up steps, and
subsequently dealing with the errors can therefore be more of a (still
strongly desirable) optimization rather than a functional necessity.

More to the point, some of the errors may be introduced by the
probabilistic nature of the AI itself. Models that may /typically/
behave well and do things like call tools as they are expected to use
may occasionally deviate from that good behavior; such modes should
therefore be handled by trying to nudge the wayward LLM back no track
rather than blowing up.
* Design
I'm hoping to just use [[id:701C146E-FE50-4C4D-9332-7B8BA81DAC25][llama.cpp]] as directly as possible through the
python bindings project. I've ended up moving away from richer
harnesses due to feeling like they are more likely to chase richer
functionality than I want and the perpsective that I should be able to
use the agent to help build itself (which should effectively dissolve
the traditional benefits of using more packaged software).
* Iteration
Now that I /seem/ to have the basics working together, I'll be looking
at improving each as a I go - much of this will revolve around
dogfooding where I ask Al to improve itself (and work on improving its
ability to improve itself).

This will typically follow a pattern of trying to refine the assorted
pieces so that they work more reliably, and then using that baseline
to capture metrics that can be used to drive optimization.
* Shared Context
One major goal within this project is to avoid anything agent
specific, and instead working out various approaches through which the
agent and myself share the same information. This will include trying
to collect any supporting documentation in common files (rather than
using files like AGENTS.md), and using the content in those files for
additional purposes such as providing prompts. Overall I want to make
sure that the agent meets me where I am, rather than needing to go
find it.

Closely related is the goal of recording and using information
locally. This was originally somewhat independent, but directly
supports the above goal in that any information which aids in applying
knowledge should be readily accessible.

All of these goals will be facilitated through the use of tools which
work with the local content.
