:PROPERTIES:
:ID:       987D73C3-C0DB-439A-860B-C161FDC295E8
:header-args: :session al
:END:
#+title: al/chat-driver
The ChatDriver is the component that orchestrates all of the messages
flowing between models and other components. Driver is used to be
somewhat analogous to a driver in compilation (rather than a device
driver), and seems slightly less likely to cause confusion in this
context when compared to an alternative like orchestrator (where
something like agent orchestration could be built on top of this).

This component is focused on communicating with a model, and
coordinating the messages with components that can be wired into
provided extension points. It should therefore be expected to contain
whatever knowledge is necessary to interact with the model, but the
definition here should remain ignorant of any of the more specialized
pieces that work on top of that.

Beyond the basics, this should enable automated interactions...maybe
"agentic loops" but my buzzword compliance has lapsed so I'm not sure
if that's accurate.

In particular beyond initial context, I'll be tentatively layering on
workflows driven by messages. Rather than requesting multiple things
at once this will allow for requesting one thing at a time where a
keyword in the response triggers the next step in the flow (for
example to request what amounts to a retrospective after completion).

Messages will be sent using [[id:C6047B7D-4B82-45B9-886A-FACBF966030B][create_chat_completion]].
* ChatDriver
This provides extension points for configuring and providing models,
and plugging in [[id:0C1AC947-C54C-4458-9F5E-F405F3DBD475][al/message-handling]].

The current interaction model tracks all messages that the have been
sent or received from the model in the session_missives property, and
records those that have yet to be sent as thunks in
retained_missives. The thunk model allows for some delayed expansion
or further processing. The immediate use for this would be to support
system prompt composition.

The on_response handler is one of the most crucial extension points as
it allows for reacting to model responses. It is called with a context
that provides a ~user_missive~ function to request additional missives
to be sent to the model. The driver itself is not passed to expose a
more controlled API (and disallow things like submit).
** Imports and MissiveSupplier
Define a type alias for a thunk which produces one or more missives.

This is used throughout to enable some deferred manipulation of the messages.
That it produces a list isn't driven by specific requirements, but
allows for more natural Maybe type behavior in python.
#+begin_src python :results silent :tangle chat_driver.py :session al
  from llama_cpp import Llama
  from llama_cpp.llama_types import ChatCompletionRequestMessage
  import logging

  MissiveSupplier = Callable[[], list[ChatCompletionRequestMessage]]
#+end_src
** Definition and Constructor
Accept arguments and initialize missive storage.
#+begin_src python :results silent :tangle chat_driver.py :session al :noweb yes
  class ChatDriver:
      def __init__(self,
                   model: Llama,
                   tools = [],
                   on_response: MessageHandler = ForEachHandler(),
                   system_prompt: MissiveSupplier = lambda: [],
                   logger = logging.getLogger(__name__)):
          self.model = model
          self.tools = tools
          self.on_response = on_response
          self.logger = logger
          self.session_missives: list[ChatCompletionRequestMessage] = []
          self.retained_missive_queue: list[MissiveSupplier] = [system_prompt]
          self.transient_missive_queue: list[MissiveSupplier] = []

      <<user-missive>>
      <<drain>>
      <<submit>>
#+end_src
*** user_missive
Provide the basic interface through which a user missive can be submitted.
#+name: user-missive
#+begin_src python :results silent
      def user_missive(self,
                       content: str):
          self.retained_missive_queue.append(lambda: [{"role": "user", "content": content}])
#+end_src
*** drain
Process queued MissiveSuppliers and log them for future session analysis
or resurrection.
#+name: drain
#+begin_src python :results silent
      def drain(self, queue):
          missives = [m for thunk in queue for m in thunk()]
          self.logger.info("Emitting: %r", missives)
          queue.clear()
          return missives
#+end_src
*** submit
Repeatedly any pending missives to the model.

This involves resolving the MissiveSupplier queues,
updating the session, and sending to the model.

The response handlers may produce new pending missives
(which would drive the loop).
#+name: submit
#+begin_src python :results silent
  def submit(self):
    while self.retained_missive_queue or self.transient_missive_queue:
      self.session_missives += self.drain(self.retained_missive_queue)
      resp = self.model.create_chat_completion(
          messages = self.session_missives + self.drain(self.transient_missive_queue),
          tools = self.tools,
          tool_choice = "auto",
          temperature=0.4,
          repeat_penalty=1.05,
      )
      choice = single_choice(resp)
      received = choice['message']
      self.logger.info("Received: %r", received)
      self.session_missives.append(received)
      on_response = self.on_response # Assign to avoid method call
      on_response({
          "user_missive": self.user_missive,
          "tool_result": lambda msg: self.transient_missive_queue.append(lambda: [msg]),
      }, choice)
#+end_src
** Logging
All missives are passed to python logging, which can be configured as documented in
standard python docs. When working in an ongoing session, force=True may be necessary
to update configuration changes.
* single_choice
Return a presumed single choice from a response or throw trying.
#+begin_src python :results silent :tangle chat_driver.py
  def single_choice(msg):
      if "choices" not in msg:
          raise TypeError(f"choices not in msg: {msg}")
      choices = msg["choices"]
      if (len(choices) != 1):
          raise TypeError(f"Only one choice is expected: {msg}")
      return choices[0]
#+end_src
