:PROPERTIES:
:ID:       FC988BB7-0319-4E5A-BE2A-7A9BEDF6F0F5
:header-args: :results output
:END:
#+title: atlassian
Atlassian products seemingly remain pretty dominant.

I've never been particularly impressed...the solutions have always
seemed fairly meh. My impression is that Atlassian largely retains a
stranglehold due to the support for the products have for some
specific enterprise needs like controls (i.e., groups like IT keeping
a tight grip on the keys), which can also introduce further tension
with utility.

I've worked with Atlassian products in many orgs with different
configurations, but have yet to see one where there's evident value -
instead they all seem to drift towards a state where there's a very
regular need to chase down people with the appropriate
access/expertise and information like reporting data that is
ostensibly within the products still ends up getting tracked
elsewhere.

These therefore fall into the bucket of things that I wouldn't tend to
use personally (where for similar needs I tend to use things like
GitLab), but set myself up so I can develop some processes.

Atlassian provides ~acli~ as an interface for their services.
* Installation
https://developer.atlassian.com/cloud/acli/guides/install-acli/
** Homebrew
#+begin_src bash :session brew :async :results silent
  brew trust --formula atlassian/acli/acli
  brew tap atlassian/homebrew-acli
  brew install acli
#+end_src
** Verification
#+begin_src bash :results silent
  acli --version
#+end_src
* Help
#+begin_src shell :results silent
  acli --help > acli_help.out
#+end_src
#+transclude: [[./acli_help.out]]
* Jira
** Help
#+begin_src bash :results silent
  acli jira --help > jira_help.out
#+end_src
#+transclude: [[./jira_help.out]]
** auth

*** Help

#+begin_src shell
  acli jira auth --help
#+end_src

#+RESULTS:
#+begin_example
Authenticate to use Atlassian CLI.

Usage:
  acli jira auth [command]

Available Commands:
  login       Authenticate with an Atlassian host.
  logout      Logout from account.
  status      Show account status.
  switch      Switch between accounts.

Flags:
  -h, --help   Show help for command

Use "acli jira auth [command] --help" for more information about a command.
#+end_example

*** login

**** Help

#+begin_src shell
  acli jira auth login --help
#+end_src

#+RESULTS:
#+begin_example
Authenticate with an Atlassian host.

Usage:
  acli jira auth login [flags]

Examples:
# Authenticate using web browser (OAuth)
$ acli jira auth login --web

# Authenticate with your email, site name and API token without scopes
$ acli jira auth login --site "mysite.atlassian.net" --email "user@atlassian.com" --token < token.txt
OR
$ echo <token> | acli jira auth login --site "mysite.atlassian.net" --email "user@atlassian.com" --token
	
# Authenticate with your email, site name and API token without scopes on Windows
$ Get-Content token.txt | .\acli.exe jira auth login --site "mysite.atlassian.net" --email "user@atlassian.com" --token

Flags:
  -e, --email string   User email is required for authentication
  -h, --help           Show help for command
  -s, --site string    Site of the Atlassian instance is required for authentication
      --token          Read token from standard input
  -w, --web            Authenticate using web browser
#+end_example

**** Token Login

I'll be looking to make use of the API token flow...first to store the credentials somewhere usable.

An API token can be created through the account settings in the Web UI.

All of the values can be thrown into environment variables and then just used by the shell.

#+begin_src shell
  echo ${ATLASSIAN_TOKEN} | acli jira auth login --site ${ATLASSIAN_SITE} --email ${ATLASSIAN_EMAIL} --token
#+end_src

#+RESULTS:
: [?25l[?2004h⣽ Authenticating...[D⣻ Authenticating...[D⢿ Authenticating...[D⡿ Authenticating...[D⣟ Authenticating...[D⣯ Authenticating...[D⣷ Authenticating...[D[2K[?2004l[?25h[?1002l[?1003l[?1006l✓ Authentication successful
:   Welcome, Matt Whipple

*** workitem

I think workitem is the subcommand that allows for getting directly to the issues and therefore
provides what amount to the primitives for command access so I'll start with that one.

**** Help

#+begin_src shell
  acli jira workitem --help
#+end_src

#+RESULTS:
#+begin_example
Jira work item commands.

Usage:
  acli jira workitem [command]

Available Commands:
  archive       Archives a work item or multiple work items.
  assign        Assign a work item(s) to an assignee(s).
  attachment    Work item attachments commands.
  clone         Create a duplicate work item(s).
  comment       Work item comments commands.
  create        Create a Jira work item.
  create-bulk   Bulk create Jira issues.
  delete        Delete a work item or multiple work items.
  edit          Edit a Jira work item or multiple work items.
  link          Link work items commands.
  list-watchers List watchers of an issue
  search        Searches for work item or multiple work items.
  transition    Transitioning a work item.
  unarchive     Unarchives work item or multiple work items.
  view          Retrieve information about Jira work items.
  watcher       Work item watcher commands.

Flags:
  -h, --help   Show help for command

Use "acli jira workitem [command] --help" for more information about a command.
#+end_example

* Confluence

** Help

#+begin_src shell
  acli confluence --help
#+end_src

#+RESULTS:
#+begin_example
Confluence Cloud commands.

Usage:
  acli confluence [command]

Available Commands:
  auth        Authenticate to use Atlassian CLI.
  blog        Confluence blog commands.
  page        Confluence page commands.
  space       Confluence space commands.

Flags:
  -h, --help   Show help for command

Use "acli confluence [command] --help" for more information about a command.
#+end_example

** auth

*** Help

#+begin_src shell
  acli confluence auth --help
#+end_src

#+RESULTS:
#+begin_example
Authenticate to use Atlassian CLI.

Usage:
  acli confluence auth [command]

Available Commands:
  login       Authenticate with an Atlassian host.
  logout      Logout from account.
  status      Show account status.
  switch      Switch between accounts.

Flags:
  -h, --help   Show help for command

Use "acli confluence auth [command] --help" for more information about a command.
#+end_example

*** Space

#+begin_src shell
  acli confluence space --help
#+end_src

#+RESULTS:
#+begin_example
Confluence space commands.

Usage:
  acli confluence space [command]

Available Commands:
  archive     Archive a Confluence space by key.
  create      Create a Confluence space.
  list        List Confluence spaces.
  restore     Restore a Confluence space from the trash or archive by key.
  update      Update details of a Confluence space, such as name, description, status, or settings by key.
  view        View details of a Confluence space.

Flags:
  -h, --help   Show help for command

Use "acli confluence space [command] --help" for more information about a command.
#+end_example

*** List

#+begin_src shell
  acli confluence space list --help
#+end_src

#+RESULTS:
#+begin_example
List Confluence spaces.

Usage:
  acli confluence space list [flags]

Examples:
# List all accessible spaces
$ acli confluence space list

# List only personal spaces
$ acli confluence space list --type personal

# List spaces with expanded information
$ acli confluence space list --expand description,homepage

# List spaces in JSON format
$ acli confluence space list --json


Flags:
      --expand string   Comma-separated list of properties to expand (description, homepage, permissions)
  -h, --help            Show help for command
      --json            Output in JSON format
      --keys string     Comma-separated list of space keys to filter by
  -l, --limit int       Maximum number of spaces to return (default 50)
      --status string   Filter spaces by status (current, archived) (default "current")
      --type string     Filter spaces by type (global, personal)
#+end_example
